USE master;
GO

IF DB_ID ('FlashCards') IS NOT NULL
BEGIN
	ALTER DATABASE FlashCards SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE FlashCards;
END

CREATE DATABASE FlashCards;
GO

USE FlashCards;
GO

DROP TABLE IF EXISTS cards
GO

BEGIN TRANSACTION
CREATE TABLE cards
	(id INT IDENTITY,
	name VARCHAR(50) NOT NULL,
	category VARCHAR(50) NOT NULL,
	description VARCHAR(500) NOT NULL,
	CONSTRAINT pk_cards PRIMARY KEY (id)
	);

	INSERT INTO cards(name, category, description) VALUES
	('Git', 'Version Control / Development Tools', 'A distributed version control system.'),
	('Repository', 'Version Control / Development Tools', 'A storage location for a project''s files and version history.'),
	('Directory/Folder', 'Version Control / Development Tools', 'A container for organizing files.'),
	('Absolute Path', 'Version Control / Development Tools', 'The complete path to a file or directory starting from the root.'),
	('Relative Path', 'Version Control / Development Tools', 'A path to a file or directory relative to the current location.'),
	('Terminal/Shell', 'Version Control / Development Tools', 'A command-line interface for interacting with a computer''s operating system.'),
	('Command Prompt', 'Version Control / Development Tools', 'A command-line interface on Windows operating systems.'),

	('Variable', 'Programming Concepts', 'A named storage location for data.'),
	('Data Types', 'Programming Concepts', 'Categories of data with specific characteristics.'),
	('Casting', 'Programming Concepts', 'Converting data from one type to another.'),
	('Namespace', 'Programming Concepts', 'A container for organizing code.'),
	('Switch/Case', 'Programming Concepts', 'A control flow structure for multiple conditional branches.'),
	('System', 'Programming Concepts', 'A namespace in .NET.'),
	('System.Collections.Generic', 'Programming Concepts', 'A namespace for generic collections.'),
	('Using', 'Programming Concepts', 'A keyword for importing namespaces.'),
	('Foreach', 'Programming Concepts', 'A loop for iterating over collections.'),
	('Type-Safe', 'Programming Concepts', 'Ensures data types are used correctly.'),

	('Methods', 'Programming Structures', 'Functions or procedures that perform specific tasks.'),
	('Statement', 'Programming Structures', 'A single line of code that performs an action.'),
	('Widening', 'Programming Structures', 'Converting data to a larger data type without data loss.'),
	('Narrowing', 'Programming Structures', 'Converting data to a smaller data type with potential data loss.'),
	('Expression', 'Programming Structures', 'A combination of values and operators that produce a result.'),
	('Scope', 'Programming Structures', 'The region of code where a variable is accessible.'),
	('Block', 'Programming Structures', 'A group of statements enclosed in curly braces.'),
	('Literal', 'Programming Structures', 'A fixed value in code.'),
	('Branches', 'Programming Structures', 'Different paths of code execution.'),
	('Condition', 'Programming Structures', 'A test that determines which branch of code to execute.'),

	('Array', 'Data Structures', 'A collection of elements with a fixed size.'),
	('Ternary', 'Data Structures', 'An operator that evaluates a condition and returns one of two values.'),
	('Loop', 'Data Structures', 'A control structure for repeating a block of code.'),
	('Collection', 'Data Structures', 'A group of elements.'),
	('Element', 'Data Structures', 'An individual item in a collection.'),
	('Increment/Decrement', 'Data Structures', 'Operators for increasing or decreasing a value.'),
	('Reserved Words', 'Data Structures', 'Words with predefined meanings in programming.'),
	('FIFO (First-In-First-Out)', 'Data Structures', 'A queuing strategy.'),
	('Queue', 'Data Structures', 'A collection that follows FIFO.'),
	('Enqueue', 'Data Structures', 'Adding an item to a queue.'),
	('Dequeue', 'Data Structures', 'Removing an item from a queue.'),
	('LIFO (Last-In-First-Out)', 'Data Structures', 'A stacking strategy.'),
	('Push', 'Data Structures', 'Adding an item to a stack.'),
	('Pop', 'Data Structures', 'Removing an item from a stack.'),
	('Key-Value Pair', 'Data Structures', 'A data structure that associates a key with a value.'),
	('HashSet', 'Data Structures', 'A collection that stores unique elements.'),
	('Dictionary', 'Data Structures', 'A collection that stores key-value pairs.'),
	('DateTime', 'Data Structures', 'A data type for representing dates and times.'),

	('String Interpolation', 'String Manipulation', 'Embedding variables in strings.'),
	('Parsing', 'String Manipulation', 'Analyzing and converting data from one format to another.'),
	('Break/Continue', 'String Manipulation', 'Control flow statements in loops.'),
	('Split', 'String Manipulation', 'Dividing a string into substrings.'),
	('For', 'String Manipulation', 'A loop that iterates a specific number of times.'),
	('While', 'String Manipulation', 'A loop that repeats while a condition is true.'),
	('Do-While', 'String Manipulation', 'A loop that executes at least once.'),

	('Value Type', 'Object-Oriented Programming', 'A data type that stores its value directly.'),
	('Reference Type', 'Object-Oriented Programming', 'A data type that stores a reference to its value.'),
	('Stack', 'Object-Oriented Programming', 'A memory area for function call and local variable storage.'),
	('Heap', 'Object-Oriented Programming', 'A memory area for dynamic memory allocation.'),
	('Immutability', 'Object-Oriented Programming', 'The inability to change the value of an object.'),
	('Class', 'Object-Oriented Programming', 'A blueprint for creating objects.'),
	('Object', 'Object-Oriented Programming', 'An instance of a class.'),
	('New', 'Object-Oriented Programming', 'Keyword for creating objects.'),
	('Substring', 'Object-Oriented Programming', 'A part of a string.'),
	('Object-Oriented Programming (OOP)', 'Object-Oriented Programming', 'A programming paradigm that uses objects and classes for modeling.'),
	('Abstraction', 'Object-Oriented Programming', 'The process of simplifying complex systems by modeling essential features.'),
	('Encapsulation', 'Object-Oriented Programming', 'The bundling of data and methods into a single unit (object).'),
	('Inheritance', 'Object-Oriented Programming', 'The mechanism that allows one class to inherit properties and methods from another.'),
	('Polymorphism', 'Object-Oriented Programming', 'The ability to present the same interface for different data types.'),

	('Big O Notation', 'Algorithm Analysis', 'A notation used to describe the upper bound of an algorithm''s time complexity.'),
	('Calling Methods', 'Algorithm Analysis', 'Invoking functions or procedures within a program.'),

	('Namespace', 'Access Modifiers / Class Members', 'A container for organizing code.'),
	('Public', 'Access Modifiers / Class Members', 'An access modifier that allows unrestricted access.'),
	('Private', 'Access Modifiers / Class Members', 'An access modifier that restricts access to within the defining class.'),
	('Properties', 'Access Modifiers / Class Members', 'Class members that provide controlled access to object attributes.'),
	('Computed/Calculated/Derived Properties', 'Access Modifiers / Class Members', 'Properties whose values are calculated based on other data.'),
	('Constructor', 'Access Modifiers / Class Members', 'A special method used to initialize objects.'),
	('Overloading', 'Access Modifiers / Class Members', 'Defining multiple methods with the same name but different parameters.'),
	('Get/Set', 'Access Modifiers / Class Members', 'Methods used to access or modify property values.'),

	('Parent/Super/Base', 'Inheritance and Class Hierarchy', 'The parent class in an inheritance hierarchy.'),
	('Child/Sub/Derived', 'Inheritance and Class Hierarchy', 'A class that inherits from another class.'),
	('Inheritance', 'Inheritance and Class Hierarchy', 'The mechanism by which one class inherits properties and behaviors from another.'),
	('Protected', 'Inheritance and Class Hierarchy', 'An access modifier that allows access within the class and derived classes.'),
	('Static', 'Inheritance and Class Hierarchy', 'A modifier that indicates a member belongs to the class, not an instance.'),
	('Virtual', 'Inheritance and Class Hierarchy', 'A modifier that indicates a method can be overridden in derived classes.'),
	('Override', 'Inheritance and Class Hierarchy', 'A keyword used to provide a new implementation for a base class method.'),
	('Base', 'Inheritance and Class Hierarchy', 'A keyword for invoking a base class constructor or method.'),
	('Is-A', 'Inheritance and Class Hierarchy', 'A relationship between a derived class and its base class.'),
	('Parameterized Constructors', 'Inheritance and Class Hierarchy', 'Constructors that accept parameters.'),
	('Object', 'Inheritance and Class Hierarchy', 'The root class for all classes in C#.'),

	('Polymorphism', 'Interfaces and Polymorphism', 'The ability to use objects of different classes through a common interface.'),
	('Interface', 'Interfaces and Polymorphism', 'A contract that defines a set of methods a class must implement.'),
	('Implement', 'Interfaces and Polymorphism', 'The act of providing concrete implementations for interface methods.'),
	('Inherit', 'Interfaces and Polymorphism', 'The process of deriving a class from an interface.'),
	('ToString()', 'Interfaces and Polymorphism', 'A method used to convert an object to a string representation.'),

	('Readonly', 'Modifiers and Testing', 'A modifier that indicates a variable''s value cannot be changed after initialization.'),
	('Abstract', 'Modifiers and Testing', 'A modifier that indicates a class or method is incomplete and must be implemented by derived classes.'),
	('Sealed', 'Modifiers and Testing', 'A modifier that prevents further inheritance or overriding.'),
	('Internal', 'Modifiers and Testing', 'An access modifier that allows access within the same assembly.'),
	('Integration Testing', 'Modifiers and Testing', 'Testing that checks interactions between different components or modules.'),
	('Regression Testing', 'Modifiers and Testing', 'Re-testing a program after changes to ensure existing functionalities still work.'),
	('Acceptance Testing', 'Modifiers and Testing', 'Testing to verify if the system meets user-defined requirements.'),
	('Exploratory Testing', 'Modifiers and Testing', 'Informal testing to discover defects without predefined test cases.'),
    ('Manual Testing', 'Modifiers and Testing', 'Testing performed by human testers without automation.'),
    ('Automated Testing', 'Modifiers and Testing', 'Testing conducted using automated testing tools.'),
    ('Unit Testing', 'Modifiers and Testing', 'Testing individual units or components of a software.'),
	('Technical Debt', 'Modifiers and Testing', 'The cost of postponing necessary work on a software project.'),
    ('Assert', 'Modifiers and Testing', 'A statement that checks whether a condition is true.'),
    ('CollectionAssert', 'Modifiers and Testing', 'A class for asserting conditions on collections.'),
    ('TestClass', 'Modifiers and Testing', 'A class used for organizing unit tests.'),
    ('TestMethod', 'Modifiers and Testing', 'A method that contains a unit test.'),
    ('Refactor', 'Modifiers and Testing', 'Restructuring code to improve its quality without changing its external behavior.'),
    ('Code Smells', 'Modifiers and Testing', 'Indications of potential problems in code.'),
    ('Test-Driven Development (TDD)', 'Modifiers and Testing', 'A development approach where tests are written before code.'),
    ('Red / Green / Refactor', 'Modifiers and Testing', 'The TDD cycle of writing failing tests, making them pass, and improving code.'),
    ('Arrange - Act - Assert', 'Modifiers and Testing', 'The structure of a unit test.'),

    ('Agile', 'Software Development Practices', 'An iterative and flexible approach to software development.'),
    ('Waterfall', 'Software Development Practices', 'A linear and sequential approach to software development.'),
    ('Software Development Lifecycle', 'Software Development Practices', 'The process of planning, creating, testing, and maintaining software.'),
    ('XML Documentation (///)', 'Software Development Practices', 'Documentation comments in code for generating documentation.'),
    ('Sprint', 'Software Development Practices', 'A time-boxed development iteration in Agile.'),
    
    ('Code Coverage', 'Code Analysis and Error Handling', 'A metric measuring the proportion of code executed by tests.'),
    ('Try-Catch-Finally', 'Code Analysis and Error Handling', 'Error-handling mechanism in programming.'),
    ('Compile-Time (Compiler) Errors', 'Code Analysis and Error Handling', 'Errors detected by the compiler during code compilation.'),
    ('Run-Time Errors', 'Code Analysis and Error Handling', 'Errors that occur during program execution.'),
    ('Logic Errors', 'Code Analysis and Error Handling', 'Errors in the program''s logic that don''t result in immediate crashes.'),
    ('Stack Trace', 'Code Analysis and Error Handling', 'A report of the function calls made during program execution.'),
    ('Custom Exceptions', 'Code Analysis and Error Handling', 'User-defined exception types.'),
    ('Throw', 'Code Analysis and Error Handling', 'A keyword for raising exceptions.'),
    
	('Data Stream', 'File I/O and String Handling', 'A sequence of data elements.'),
    ('StreamReader', 'File I/O and String Handling', 'A class for reading character streams.'),
    ('StreamWriter', 'File I/O and String Handling', 'A class for writing character streams.'),
    ('Verbatim String (@)', 'File I/O and String Handling', 'A string that doesn''t interpret escape sequences.'),
    ('Buffer', 'File I/O and String Handling', 'A temporary storage area.'),
    
	('SELECT', 'Database Query Language and Concepts', 'SQL command for querying data.'),
    ('FROM', 'Database Query Language and Concepts', 'SQL clause specifying the data source.'),
    ('WHERE', 'Database Query Language and Concepts', 'SQL clause for filtering data.'),
    ('BETWEEN', 'Database Query Language and Concepts', 'SQL operator for specifying a range.'),
    ('AS', 'Database Query Language and Concepts', 'SQL clause for aliasing columns.'),
    ('IS NULL', 'Database Query Language and Concepts', 'SQL condition for checking if a value is null.'),
    ('IS NOT NULL', 'Database Query Language and Concepts', 'SQL condition for checking if a value is not null.'),
    ('IN', 'Database Query Language and Concepts', 'SQL operator for matching values in a list.'),
    ('LIKE', 'Database Query Language and Concepts', 'SQL operator for pattern matching.'),
    ('Server', 'Database Query Language and Concepts', 'A computer or system hosting a database.'),
    ('Database', 'Database Query Language and Concepts', 'A structured collection of data.'),
    ('Table', 'Database Query Language and Concepts', 'A database object that stores data.'),
    ('Column', 'Database Query Language and Concepts', 'A field within a database table.'),
    ('Row', 'Database Query Language and Concepts', 'A single record in a database table.'),
    ('RDBMS (Relational Database Management System)', 'Database Query Language and Concepts', 'A database system that uses a relational model.'),
    ('ORDER BY', 'Database Query Language and Concepts', 'SQL clause for sorting query results.'),
    ('ASC', 'Database Query Language and Concepts', 'Keyword used with ORDER BY to sort in ascending order.'),
    ('DESC', 'Database Query Language and Concepts', 'Keyword used with ORDER BY to sort in descending order.'),
    ('TOP', 'Database Query Language and Concepts', 'SQL keyword for limiting the number of rows returned.'),
    ('PERCENT', 'Database Query Language and Concepts', 'SQL keyword for specifying a percentage of rows to return.'),
    ('WITH TIES', 'Database Query Language and Concepts', 'SQL clause that includes rows with equal values when using TOP.'),
    ('JOIN', 'Database Joins and Keys', 'SQL operation for combining rows from multiple tables.'),
    ('INNER JOIN / JOIN', 'Database Joins and Keys', 'SQL operation that returns only matching rows from both tables.'),
    ('LEFT OUTER JOIN / LEFT JOIN', 'Database Joins and Keys', 'SQL operation that returns all rows from the left table and matching rows from the right table.'),
    ('RIGHT OUTER JOIN / RIGHT JOIN', 'Database Joins and Keys', 'SQL operation that returns all rows from the right table and matching rows from the left table.'),
    ('UNION', 'Database Joins and Keys', 'SQL operation for combining result sets from two or more SELECT statements.'),
    ('PRIMARY KEY', 'Database Joins and Keys', 'A column or set of columns that uniquely identifies each row in a table.'),
    ('FOREIGN KEY', 'Database Joins and Keys', 'A column that establishes a link between data in two tables.'),
    ('Natural Keys', 'Database Joins and Keys', 'Keys derived from the data itself.'),
    ('Surrogate Keys', 'Database Joins and Keys', 'Keys generated specifically for identification purposes.'),
    ('Cardinality', 'Database Joins and Keys', 'The number of unique values in a column.'),
    ('One-to-One', 'Database Joins and Keys', 'A relationship where each record in one table is related to only one record in another.'),
    ('One-to-Many', 'Database Joins and Keys', 'A relationship where each record in one table can be related to multiple records in another.'),
    ('Many-to-Many', 'Database Joins and Keys', 'A relationship where multiple records in one table can be related to multiple records in another.'),
    ('Crow''s Foot Notation', 'Database Joins and Keys', 'A visual notation for representing entity-relationship diagrams.'),
    
	('Table Constraints', 'Database Constraints and Operations', 'Rules applied to columns in a database table.'),
    ('NULL / NOT NULL', 'Database Constraints and Operations', 'Constraints specifying whether a column can contain null values.'),
    ('UNIQUE', 'Database Constraints and Operations', 'Constraint ensuring that values in a column are unique.'),
    ('PRIMARY KEY', 'Database Constraints and Operations', 'Constraint defining a unique identifier for a table.'),
    ('FOREIGN KEY', 'Database Constraints and Operations', 'Constraint establishing a link to another table.'),
    ('DEFAULT', 'Database Constraints and Operations', 'Constraint specifying a default value for a column.'),
    ('CHECK', 'Database Constraints and Operations', 'Constraint that validates data using a Boolean expression.'),
    ('INDEX', 'Database Constraints and Operations', 'A data structure that improves the speed of data retrieval.'),
    ('ACID', 'Database Constraints and Operations', 'Properties of database transactions (Atomicity, Consistency, Isolation, Durability).'),
    ('Transaction', 'Database Constraints and Operations', 'A sequence of SQL statements treated as a single unit of work.'),
    ('COMMIT', 'Database Constraints and Operations', 'SQL command to make changes to a database permanent.'),
    ('ROLLBACK', 'Database Constraints and Operations', 'SQL command to undo changes in a transaction.'),
    ('DELETE', 'Database Constraints and Operations', 'SQL command for removing rows from a table.'),
    ('INSERT', 'Database Constraints and Operations', 'SQL command for adding new rows to a table.'),
    ('UPDATE', 'Database Constraints and Operations', 'SQL command for modifying existing rows in a table.'),
    
	('IDENTITY', 'Database Management and Definitions', 'A property used to generate unique values for a column.'),
    ('DDL (Data Definition Language)', 'Database Management and Definitions', 'SQL statements for defining database structures.'),
    ('DML (Data Manipulation Language)', 'Database Management and Definitions', 'SQL statements for manipulating data.'),
    ('DCL (Data Control Language)', 'Database Management and Definitions', 'SQL statements for controlling access to data.'),
    ('ERD (Entity Relationship Diagrams)', 'Database Management and Definitions', 'Visual representations of database entities and their relationships.'),
    ('TFLA (Three and Four Letter Acronyms)', 'Database Management and Definitions', 'A humorous reference to the abundance of acronyms in the IT field.'),
    ('Normalization', 'Database Management and Definitions', 'The process of organizing database tables to reduce data redundancy.'),
    ('Schema/Data', 'Database Management and Definitions', 'The structure and organization of a database.'),
    ('CREATE/DROP/ALTER for TABLE and DATABASE', 'Database Management and Definitions', 'SQL commands for creating, deleting, or modifying tables and databases.'),
    ('GO', 'Database Management and Definitions', 'A SQL batch separator.'),
   
    ('OUTPUT', 'Database Output and Data Access', 'SQL clause for returning result sets from INSERT, UPDATE, or DELETE statements.'),
    ('DAO (Data Access Object)', 'Database Output and Data Access', 'A design pattern for separating data access logic from business logic.'),
    ('Connection String', 'Database Output and Data Access', 'A string that specifies database connection parameters.'),
   
	('ExecuteNonQuery', 'Database Commands and Parameters', 'A method for executing SQL commands that don''t return data.'),
    ('ExecuteScalar', 'Database Commands and Parameters', 'A method for executing SQL commands that return a single value.'),
    ('Command.Parameter.AddWithValue', 'Database Commands and Parameters', 'A method for adding parameters to SQL commands.'),
    ('Nullable Types (int?, double?, etc.)', 'Database Commands and Parameters', 'Data types that can hold null values.'),
    
	('SQL Injection', 'Security and Testing', 'A security vulnerability involving malicious SQL code injection.'),
    ('Salt', 'Security and Testing', 'Random data added to password hashes for security.'),
    ('Hashing', 'Security and Testing', 'A process that converts data into a fixed-size string of characters.'),
    ('Integration Testing', 'Security and Testing', 'Testing that checks interactions between different components.'),
    ('Encryption', 'Security and Testing', 'The process of converting data into a secure format.'),
    ('Single Key Encryption', 'Security and Testing', 'Using a single key for both encryption and decryption.'),
    ('Open Key Encryption', 'Security and Testing', 'A type of encryption where the encryption key is publicly available.'),
    ('Dependency Injection', 'Security and Testing', 'A design pattern for injecting dependencies into objects.'),
    ('Assembly Initialize / Assembly Cleanup', 'Security and Testing', 'Methods used for setup and teardown in unit testing.'),
    ('Test Initialize / Test Cleanup', 'Security and Testing', 'Methods used for setup and teardown in unit testing.'),
    
	('HTTP (Hypertext Transport Protocol)', 'Web Technologies', 'A protocol for transferring data on the web.'),
    ('REST (Representational State Transfer)', 'Web Technologies', 'A design style for building web services.'),
    ('JSON (JavaScript Object Notation)', 'Web Technologies', 'A lightweight data interchange format.'),
    ('IP (Internet Protocol)', 'Web Technologies', 'A set of rules for routing data across networks.'),
    ('IP Address', 'Web Technologies', 'A numerical label assigned to each device on a network.'),
    ('DNS (Domain Name Servers)', 'Web Technologies', 'Servers that translate domain names into IP addresses.'),
    ('Serialize / Deserialize', 'Web Technologies', 'Converting data to/from a format suitable for transmission.'),
    ('API (Application Programming Interface)', 'Web Technologies', 'A set of rules and protocols for building software.'),
    ('TLS (Transport Layer Security)', 'Web Technologies', 'A protocol for securing data transmitted over networks.'),
    ('URL (Universal Resource Locator)', 'Web Technologies', 'A web address.'),
    ('localhost (127.0.0.1)', 'Web Technologies', 'A special IP address representing the local machine.'),
    ('Status Codes', 'Web Technologies', 'Numeric codes indicating the outcome of an HTTP request.'),
    ('Web Server', 'Web Technologies', 'A server that serves web content.'),
    ('Web Service', 'Web Technologies', 'A service accessible over the web.'),
    ('Request/Response', 'Web Technologies', 'The communication pattern in web interactions.'),
    
	('POST', 'HTTP Methods', 'HTTP method for sending data to a server to create a new resource.'),
    ('PUT', 'HTTP Methods', 'HTTP method for updating an existing resource on a server.'),
    ('DELETE', 'HTTP Methods', 'HTTP method for deleting a resource on a server.'),
    
	('Internet Engineering Task Force (IETF)', 'Internet and Standards', 'An organization that develops internet standards.'),
    ('Request For Comment (RFC)', 'Internet and Standards', 'A publication describing internet protocols.'),
    ('RestSharp', 'Internet and Standards', 'A popular library for making RESTful HTTP requests.'),
    
	('Controller', 'Software Architecture and Design', 'In the context of MVC, it handles user input and interaction.'),
    ('Model', 'Software Architecture and Design', 'In the context of MVC, it represents the application''s data and logic.'),
    ('View', 'Software Architecture and Design', 'In the context of MVC, it presents the data to the user.'),
    ('MVC (Model-View-Controller)', 'Software Architecture and Design', 'A design pattern for organizing code in software development.'),
    ('Query String', 'Software Architecture and Design', 'A part of a URL that passes data to the server.'),
    ('Optional Parameters', 'Software Architecture and Design', 'Parameters that don''t have to be provided when calling a function.'),
    ('Framework', 'Software Architecture and Design', 'A pre-built structure for developing applications.'),
    ('Content Negotiation', 'Software Architecture and Design', 'The process of determining the best content type for a response.'),
    ('Attributes / Tags / Decorations', 'Software Architecture and Design', 'Annotations used to add metadata to code.');
COMMIT TRANSACTION